version: 2
jobs:
  build:
    macos:
      xcode: 12.3.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - v2-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.konan
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

      - run: ./gradlew build allTests installBinary
      - run: resharkercli --help
      - run: resharkercli version
      - run: resharkercli current --help
      - run: resharkercli current key
      - run: resharkercli project --help
      - run: resharkercli project list
      - run: resharkercli parse --help
      - run: resharkercli parse key "dirty/string/with a key/RES-1/somewhere"
